Automated database creation and migration
mempool/mempool pull request #1003
Opened 2021-12-11 00:42 UTC by softsimon

fixes #1002

Removed the database structure SQL-file and created to a fully automated database creation and migration service. A new table called "state" will keep various information like the current mempool table schema version and the current Liquid pegs sync header.

When the backend starts up it will:
1. Check if the base table exists (`statistics`), if not, it will create all tables and run migrations
2. It will check if the new "state" table exist and check for the current schema version. It will run available migrations up to the latest version.

The base version is 0 and the 2.3 release will bump the database version to 1... so when the backend detects that a '`statistics`' table already exists, but not the new '`state`', it will assume version 0 and run the migration to 1 which includes creating the new tables (`state, elements_pegs`) and migrating the statistics data (if not on Liquid backend).

This pave way for very easy future database schema updates just by adding more queries to the migration service and bump the schema version. Example:

Bump the version:
```
private static currentVersion = 2;
```

Add to method `getMigrationQueriesFromVersion`:
```
if (version < 2) {
   queries.push(`CREATE TABLE version_2_table (id int(11) NOT NULL)`);
}
```

2021-12-11 01:03 UTC, wiz commented
This PR isn't ready for testing yet since this is only the backend component, of course this feature requires updates to backend Dockerfile and the documentation etc. so I will make those changes and push to this PR branch

2021-12-11 04:40 UTC, knorrium requested changes

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +  public async $initializeOrMigrateDatabase(): Promise<void> {
@softsimon I don't like how this method has multiple responsibilities. IMO it should be split into `initializeDatabase` and `migrateDabase` so we know exactly what's being done.

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +        await connection.query<any>({ sql: query, timeout: this.queryTimeout });
@softsimon shouldn't this be in a try-catch? what happens if one of the queries fail? we'll probably want to rollback and/or exit early.

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +      logger.info(`Initial database tables has been created`);
```suggestion
      logger.info(`Initial database tables have been created`);
```

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +          await connection.query<any>({ sql: query, timeout: this.queryTimeout });
@softsimon same as the previous comment on try-catch

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +        logger.info(`Database schema has been migrated to the latest version (${DatabaseMigration.currentVersion})`);
```suggestion
        logger.info(`Database schema has been migrated from ${databaseSchemaVersion} to the latest version: (${DatabaseMigration.currentVersion})`);
```

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +        logger.info(`Database schema has been migrated to the latest version (${DatabaseMigration.currentVersion})`);
@softsimon I think it's important to log what version we are migrating from as well

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +      logger.info(`Database schema has been migrated to the latest version (${DatabaseMigration.currentVersion})`);
```suggestion
      logger.info(`Database schema has been migrated from ${databaseSchemaVersion} to the latest version: (${DatabaseMigration.currentVersion})`);
```

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +  private async $getSchemaVersionFromDatabase(): Promise<number> {
@softsimon all these methods should have some better error handling

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +    const query = `SELECT number FROM state WHERE name = 'schema_version';`;
@softsimon SQL queries should be imported as constants so it's easier to maintain and track  vs sql changes

2021-12-11 04:40 UTC, knorrium commented on backend/src/api/database-migration.ts
> +    queries.push(`CREATE TABLE IF NOT EXISTS statistics (
@softsimon see how clean this would be if the queries are extracted from here

2021-12-11 04:43 UTC, knorrium requested changes

2021-12-11 04:43 UTC, knorrium commented on backend/src/api/database-migration.ts
> +    if (version < 1) {
@softsimon IMO the the version should also be mapped to semver somewhere so we know that 0 = < 2.3.0 and 1 >= 2.3.0

2021-12-17 06:39 UTC, wiz commented
btw don't merge this, let me do it since I have to manually do SQL commands on the production servers to avoid corrupting the database

2021-12-23 20:37 UTC, softsimon commented
So since we already ran the `statistics` data migration SQL on the production servers, we need to do the other new SQL queries manually as well, for the migration not to be run twice and ruin the data.

How to upgrade production:
1. Run the new SQL-queries below in order
2. Upgrade and restart the backend

Liquid backend only:
1. Copy the `block` height number from the now deprecated `last_elements_block` table and add it to the new `state` table either in the INSERT `last_elements_block` value query or update the row, before restarting the backend.

Queries:
```
CREATE TABLE IF NOT EXISTS state (
        name varchar(25) NOT NULL,
        number int(11) NULL,
        string varchar(100) NULL
      ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

```
INSERT INTO state VALUES('schema_version', 0, NULL);
```
```
INSERT INTO state VALUES('last_elements_block', 0, NULL);
```

2021-12-23 21:49 UTC, wiz approved these changes
Tested ACK @ 91e30fbc
Tested ACK @ `v2.3.0-dev3` tag (from `wiz/database-migration-feature` branch) using @knorrium/umbrel#mempool_230 fork on Raspberry Pi 
Works well on Umbrel using Docker, and Works well upgrading SQL database on production server, took about 40 seconds:
```
Dec 23 21:46:10 [31725] INFO: Database connection established.
Dec 23 21:46:50 [31725] INFO: Database schema have been migrated from version 0 to 1 (latest version)
```

2021-12-23 21:50 UTC, merged

2021-12-24 18:12 UTC, wiz commented
Upgraded prod servers manually using this command:
```
for i in mempool mempool_testnet mempool_signet mempool_liquid;do echo "
CREATE TABLE IF NOT EXISTS state ( name varchar(25) NOT NULL, number int(11) NULL, string varchar(100) NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO state VALUES('schema_version', 1, NULL);
" | mysql -u root -p $i;done
echo "INSERT INTO state VALUES('last_elements_block', (SELECT block FROM last_elements_block), NULL);"|mysql -u root -p mempool_liquid
```