Create indexing progress sticky notification
mempool/mempool pull request #1596
Opened 2022-05-02 08:31 UTC by nymkappa

<img width="1496" alt="Screen Shot 2022-05-02 at 5 29 39 PM" src="https://user-images.githubusercontent.com/9780671/166206589-69ed7541-5732-45f2-8422-24228f27fb5b.png">
<img width="326" alt="Screen Shot 2022-05-02 at 5 29 25 PM" src="https://user-images.githubusercontent.com/9780671/166206593-da748c59-6d3b-4be6-8362-6e2c8867b26b.png">

2022-05-02 22:15 UTC, wiz requested changes
There is a UI bug where the status badge is in a random location on the screen, shouldn't it be next to or under the mempool logo
![image](https://user-images.githubusercontent.com/232186/166335618-ef33fbe2-6a8d-4944-b1fd-9bdeca2e301d.jpeg)

2022-05-06 12:18 UTC, softsimon requested changes
I too agree it should be moved to either the top left, top middle or simply at the main dashboard next to indexing in progress. The latter makes more sense to me.

2022-05-09 09:39 UTC, nymkappa commented
Moved the notification to the top left

<img width="1496" alt="Screen Shot 2022-05-09 at 11 38 46 AM" src="https://user-images.githubusercontent.com/9780671/167383605-98c9a3ab-4d31-4f5e-a3e3-180ef3e36f75.png">

2022-05-10 11:33 UTC, wiz requested changes
Tested ACK on the badge functionality @ v2.4.0-dev [[e405e5a7](https://github.com/mempool/mempool/commit/e405e5a7)], but NACK on the badge location because it blocks various UI elements 
<img src="https://user-images.githubusercontent.com/232186/167618731-76ec57dd-3df2-4672-aea7-1240cc22a755.jpg">
<img width="241" alt="Screen Shot 2022-05-10 at 20 27 06" src="https://user-images.githubusercontent.com/232186/167618515-0a319e00-e0df-4f8f-82f8-a89001b11394.png">

Could you just move it over to the left on mobile, and more towards the top on desktop? For example with this quick change from `top: 75px` to `top: 50px` it no longer blocks the graphs page buttons

<img width="229" alt="Screen Shot 2022-05-10 at 20 27 11" src="https://user-images.githubusercontent.com/232186/167618825-05f7271c-5939-4daa-abb7-82f1abae9bb9.png">

2022-05-10 12:38 UTC, nymkappa commented
> Tested ACK on the badge functionality @ v2.4.0-dev [[e405e5a7](https://github.com/mempool/mempool/commit/e405e5a7)], but NACK on the badge location because it blocks various UI elements ![](https://user-images.githubusercontent.com/232186/167618731-76ec57dd-3df2-4672-aea7-1240cc22a755.jpg) <img alt="Screen Shot 2022-05-10 at 20 27 06" width="241" src="https://user-images.githubusercontent.com/232186/167618515-0a319e00-e0df-4f8f-82f8-a89001b11394.png">
> 
> Could you just move it over to the left on mobile, and more towards the top on desktop? For example with this quick change from `top: 75px` to `top: 50px` it no longer blocks the graphs page buttons
> 
> <img alt="Screen Shot 2022-05-10 at 20 27 11" width="229" src="https://user-images.githubusercontent.com/232186/167618825-05f7271c-5939-4daa-abb7-82f1abae9bb9.png">

Haha nice catch I forgot about the network dropdown on prod!

2022-05-10 12:53 UTC, nymkappa commented
How about this. Now it's fixed to the page, not sticky anymore. I forced pushed.

#### Desktop
<img width="1496" alt="Screen Shot 2022-05-10 at 2 49 50 PM" src="https://user-images.githubusercontent.com/9780671/167632441-4bc29165-364b-47df-9abb-fe2a4dcf5000.png">

#### Tablet
<img width="809" alt="Screen Shot 2022-05-10 at 2 50 19 PM" src="https://user-images.githubusercontent.com/9780671/167632455-15509d4d-34b0-49ec-b5db-f70b5a4af2f8.png">

#### Mobile
<img width="372" alt="Screen Shot 2022-05-10 at 2 50 31 PM" src="https://user-images.githubusercontent.com/9780671/167632475-16693c92-a26d-4456-8855-ed5355504ecb.png">

2022-05-10 14:01 UTC, wiz approved these changes
Tested ACK @ v2.4.0-dev [[df177e0e](https://github.com/mempool/mempool/commit/df177e0e)]

2022-05-10 14:02 UTC, merged