Liquid UX fixes
mempool/mempool pull request #1699
Opened 2022-05-20 22:07 UTC by softsimon

fixes #1683
fixes #1681

2022-05-23 07:48 UTC, nymkappa commented on frontend/src/app/components/block/block.component.html
>                </ng-template>
This fix is correct, other changes must be reverted. See https://github.com/mempool/mempool/pull/1707

2022-05-23 07:49 UTC, nymkappa requested changes

2022-05-23 07:49 UTC, nymkappa commented on frontend/src/app/components/block/block.component.html
> +              <tr *ngIf="network !== 'liquid' && network !== 'liquidtestnet'">
This fix is correct, other changes must be reverted. See https://github.com/mempool/mempool/pull/1707

2022-05-27 09:14 UTC, wiz approved these changes
Tested ACK @ v2.4.0-dev [[63ab2d7c](https://github.com/mempool/mempool/commit/63ab2d7c)]

2022-05-27 09:15 UTC, merged