fix various RTL layout issues
mempool/mempool pull request #1931
Opened 2022-06-25 21:52 UTC by TechMiX

Fixes #1921

2022-07-05 23:14 UTC, wiz requested changes
Tested NACK @ v2.4.1-dev [[e0e2a2a6](https://github.com/mempool/mempool/commit/e0e2a2a6)]

Hi @TechMiX,
Thanks for working on this, but while testing we found some issues on the LTR version of the site introduced by this PR

### Expected
<img width="1120" alt="Screen Shot 2022-07-06 at 1 11 41" src="https://user-images.githubusercontent.com/232186/177431762-c3192a42-880c-4b10-9d18-3a79989ac406.png">

### Actual
<img width="1116" alt="Screen Shot 2022-07-06 at 1 11 35" src="https://user-images.githubusercontent.com/232186/177431765-d5bb5a8d-1543-4d86-8cd3-e7e400b9236d.png">

2022-07-06 11:05 UTC, TechMiX commented
I see. I reverted the changes on the transaction page. @wiz

2022-07-06 18:21 UTC, knorrium commented
Tested ACK @ v2.4.1-dev [2911fbe5]

2022-07-06 18:28 UTC, wiz approved these changes

2022-07-06 18:29 UTC, merged