Simon/lightning pr
mempool/mempool pull request #1976
Opened 2022-07-06 10:08 UTC by nymkappa

2022-07-06 14:39 UTC, softsimon commented
Ready to test :)

2022-07-06 21:32 UTC, wiz commented
please rebase and increment db schema version

2022-07-08 22:02 UTC, knorrium commented
@softsimon can you update the lock file?

2022-07-08 22:37 UTC, wiz commented
can you please fix page title and SEO metadata for /lightning

2022-07-10 12:50 UTC, wiz requested changes
Tested ACK @ v2.4.1-dev [[18030ba3](https://github.com/mempool/mempool/commit/18030ba3)]

A few very minor requested changes, but tested and reviewed OK :rocket:

2022-07-10 12:50 UTC, wiz commented on backend/src/api/explorer/channels.routes.ts
> +        res.status(501).send('Missing parameter: public_key');
```suggestion
        res.status(400).send('Missing parameter: public_key');
```

2022-07-10 12:50 UTC, wiz commented on backend/src/api/explorer/channels.routes.ts
> +        res.status(500).send('Not an array');
```suggestion
        res.status(400).send('Not an array');
```

2022-07-10 12:50 UTC, wiz commented on backend/src/api/explorer/general.routes.ts
> +      res.status(501).send('Missing parameter: searchText');
```suggestion
      res.status(400).send('Missing parameter: searchText');
```

2022-07-10 12:51 UTC, wiz approved these changes
Tested ACK @ v2.4.1-dev [[18030ba3](https://github.com/mempool/mempool/commit/18030ba3)]

2022-07-10 13:08 UTC, wiz commented
CI found a bug in the liquid block page, should fix later in separate PR 

<img width="946" alt="Screen Shot 2022-07-10 at 15 07 18" src="https://user-images.githubusercontent.com/232186/178146171-40462720-228e-4786-b3fa-e0c42217f549.png">

2022-07-10 13:08 UTC, merged