feature: add /block/:hash/raw api route
mempool/mempool pull request #2181
Opened 2022-07-25 19:51 UTC by oleonardolima

### Description
As decribed in #2180 this PR adds the /block/:hash/raw API route, it's now available when using mempool backend, with Bitcoin Core RPC.

In the production environment and using `esplora` as backend, it's still being ignored and must be redirected by the nginx configuration.

It also updates the doc message indicating that the type must differ by each backend used:
- esplora: block in binary representation
- bitcoin core rpc: block in hex

2022-07-25 20:05 UTC, softsimon commented on docker/backend/Dockerfile
> +FROM node:17.9.1-buster-slim AS builder
Is the change to the Dockerfile intended?

I don't see the relation to the PR so should be reverted.

2022-07-25 20:10 UTC, softsimon requested changes
Our goal for the Mempool API is to be identical to the Esplora API (when possible) so it doesn't matter which backend you run https://github.com/Blockstream/esplora/blob/master/API.md

So you need to change it so our bitcoin core based api returns the data in binary.

2022-07-25 20:23 UTC, oleonardolima commented
> Our goal for the Mempool API is to be identical to the Esplora API (when possible) so it doesn't matter which backend you run https://github.com/Blockstream/esplora/blob/master/API.md
> 
> So you need to change it so our bitcoin core based api returns the data in binary.

Sure, I'll work on it

2022-07-27 20:20 UTC, oleonardolima commented
> Our goal for the Mempool API is to be identical to the Esplora API (when possible) so it doesn't matter which backend you run https://github.com/Blockstream/esplora/blob/master/API.md
> 
> So you need to change it so our bitcoin core based api returns the data in binary.

@

> > Our goal for the Mempool API is to be identical to the Esplora API (when possible) so it doesn't matter which backend you run https://github.com/Blockstream/esplora/blob/master/API.md
> > So you need to change it so our bitcoin core based api returns the data in binary.
> 
> Sure, I'll work on it

@softsimon Sorry for the delay, I've updated it now 😁

2022-07-27 20:22 UTC, oleonardolima commented
I've tested it locally with curl, postman, and with the following snippet:
``` rust
use std::ops::Deref;

use bitcoin::{consensus::deserialize, Block};

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    env_logger::init();

    let hash = "1a72d2a7d9c7f0894b8e83344ec5d73e0c58588a7bee95f8552feb39423bca9e";
    let url = format!("http://localhost:8999/api/v1/block/{}/raw", hash);

    let res = reqwest::get(url).await?;
    log::debug!("{:#?}", res);

    let res_bytes = res.bytes().await?;
    log::debug!("{:#?}", res_bytes);
    let block: Block = deserialize(res_bytes.deref()).unwrap();
    // log::debug!("{:#?}", block);
    print!("{:#?}", block);

    Ok(())
}

```

2022-07-27 21:33 UTC, softsimon approved these changes
tested ACK @ v2.5.0-dev [[a9248a5f](https://github.com/mempool/mempool/commit/a9248a5f)]

2022-07-27 21:33 UTC, softsimon commented on backend/src/api/bitcoin/bitcoin.routes.ts
> +      res.setHeader('content-type', 'text/plain');
```suggestion
      res.setHeader('content-type', 'application/octet-stream');
```

2022-07-27 22:46 UTC, wiz approved these changes
Tested ACK @ d66cc8a213f9e4f78197133ebc7db95f13617b4f

Output matches esplora exactly :+1:

2022-07-27 22:47 UTC, merged