Refactor the LN backend and add more logs
mempool/mempool pull request #2266
Opened 2022-08-08 07:27 UTC by nymkappa

This PR cleans up a bit the lightning backend, mostly the node and channel updater code.
I've also added logs so we get a progress update every 10 seconds approximately.

2022-08-08 07:28 UTC, nymkappa commented on backend/src/api/explorer/nodes.api.ts
> +   public async $setNodesInactive(graphNodesPubkeys: string[]): Promise<void> {
This function `$setNodesInactive` is not yet used, you can ignore it for this PR.

2022-08-08 07:29 UTC, nymkappa commented on backend/src/config.ts
> +    STATS_REFRESH_INTERVAL: number;
Renamed `NODE_STATS_...` to `NETWORK_STATS_...` to avoid any future confusion

2022-08-08 08:30 UTC, nymkappa commented
There may be an issue right now, I'm checking. Related to https://github.com/mempool/mempool/issues/2256.
Seems to work fine on master, so this PR may have an issue.

```
Aug  8 10:28:26 [90104] INFO: <lightning> Importing historical lightning stats
/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:128
                            err = new Error(decodedResponse.error.message || '');
                                  ^

Error: JSON integer out of range
    at /Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:128:35
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:125:25)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: -1
}
```

2022-08-09 08:30 UTC, nymkappa commented
Creates and fixes https://github.com/mempool/mempool/issues/2256

2022-08-10 12:13 UTC, wiz requested changes
Tested NACK @ ef6c380
```
Aug 10 12:07:15 node201.fra  mempool[92168]: INFO <testnet> Fetching hourly price history from exchanges and saving missing ones into the database, this may take a while
Aug 10 12:07:15 node201.fra  mempool[91346]: ERR <lightning> $saveNode() error: Unknown column 'status' in 'field list'
Aug 10 12:07:15 node201 syslogd: last message repeated 300 times
Aug 10 12:07:15 node201.fra  mempool[90767]: NOTICE Inserted 1 daily historical prices into the db
Aug 10 12:07:15 node201.fra  mempool[91346]: ERR <lightning> $saveNode() error: Unknown column 'status' in 'field list'
Aug 10 12:07:16 node201 syslogd: last message repeated 52 times
Aug 10 12:07:16 node201.fra  mempool[90767]: INFO Fetching hourly price history from exchanges and saving missing ones into the database, this may take a while
Aug 10 12:07:16 node201.fra  mempool[91346]: ERR <lightning> $saveNode() error: Unknown column 'status' in 'field list'
Aug 10 12:07:17 node201 syslogd: last message repeated 9078 times
```

2022-08-10 13:01 UTC, wiz commented
Replaced by #2267

2022-08-10 13:01 UTC, closed without merging