Disable mempool config
mempool/mempool pull request #2378
Opened 2022-08-23 16:32 UTC by softsimon

fixes #2090

New config option that disables all mempool, block indexing and mempool stats activity including the routes. Intended for Lightning backend, default is enabled = true.

```
  "MEMPOOL": {
    "ENABLED": false,
```

2022-08-28 07:20 UTC, nymkappa commented
Tested ACK @ 9c0542351f67a95a3da4ec3d0a9e0786e73486c9

2022-08-28 07:22 UTC, nymkappa requested changes
You did not update docker configuration files but it works fine Can be merged once files are updated.

Tested ACK @ 9c0542351f67a95a3da4ec3d0a9e0786e73486c9

2022-08-28 13:52 UTC, softsimon commented
Added docker config. Hope I did it right, just played by the ear.

2022-08-30 07:35 UTC, nymkappa commented
You're missing `mempool/docker/README.md` but I think otherwise you're good. @knorrium may double check as well.

2022-08-30 07:35 UTC, nymkappa requested changes
You're missing `mempool/docker/README.md` but I think otherwise you're good. @knorrium may double check as well.

2022-08-31 07:27 UTC, nymkappa approved these changes

2022-09-02 05:50 UTC, knorrium requested changes

2022-09-02 05:50 UTC, knorrium commented on backend/src/__fixtures__/mempool-config.template.json
> +    "ENABLED": true,
```suggestion

```

2022-09-02 05:50 UTC, knorrium commented on backend/src/__fixtures__/mempool-config.template.json
> +    "ENABLED": true,
This is duplicated above

2022-11-21 08:30 UTC, wiz approved these changes
Tested ACK @ 5957b71774e16d027919a531a1854e31bd1a7515

2022-11-21 08:31 UTC, merged