Fix overflowing tx on mobile - use monospace fonts
mempool/mempool pull request #2429
Opened 2022-08-29 09:13 UTC by nymkappa

This PR should be carefully reviewed by at least two persons because it touches the transaction component. Transactions input/output list has now slightly bigger padding between each rows to properly fit the layer2 tag.

#### Currently the tx list overflows because of the new layer2 tags

<img width="392" alt="image" src="https://user-images.githubusercontent.com/9780671/187166750-cc1221fe-b94e-4a69-8f32-aaf6a06b21ea.png">

#### PR result

**Mobile channel page**
<img width="387" alt="image" src="https://user-images.githubusercontent.com/9780671/187166480-2ff8f707-ca46-4038-ac90-42ee0bf9871d.png">

**Desktop channel page**
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/9780671/187166900-86c72019-09bc-4f8a-a6fd-9d95e8d02945.png">

2022-08-29 09:58 UTC, softsimon commented
Added some margin below address labels as I think it becomes too tight and merged.

2022-08-29 09:58 UTC, softsimon commented
Added some margin below address labels as I think it becomes too tight and merged.

2022-08-29 10:34 UTC, softsimon commented
I am not a fan of this new compressed look without margin between each address and their labels. 

<img width="579" alt="Screen Shot 2022-08-29 at 12 33 55" src="https://user-images.githubusercontent.com/8561090/187182334-26e7c578-d860-45f3-a5d3-b743846bad5d.png">

2022-08-31 12:56 UTC, wiz requested changes
NACK for reasons Simon listed

2022-08-31 15:52 UTC, closed without merging

2022-08-31 15:54 UTC, nymkappa commented
@softsimon Please give this bug a shot