show CPFP info for mined transactions
mempool/mempool pull request #2737
Opened 2022-11-27 08:54 UTC by mononaut

This PR adds support for calculating and indexing CPFP info (effective fee rate, ancestors and descendants) for transactions in mined blocks.

<img width="1158" alt="mined-cpfp" src="https://user-images.githubusercontent.com/83316221/204126537-c4496d52-1e7b-47f8-aa5a-2da6d53bf73e.png">

The feature can be enabled using a new backend config setting `MEMPOOL.TRANSACTION_INDEXING` (default false), which keeps the last `INDEXING_BLOCKS_AMOUNT` blocks indexed.

Data is stored in two new tables, `cpfp_clusters` and `transactions`. 

The PR also extends the in-mempool CPFP data to include all relevant descendants instead of a single `bestDescendant`.

<img width="1158" alt="mempool-descendants" src="https://user-images.githubusercontent.com/83316221/204126331-ae8a0745-a07f-4c26-aa1e-fe64a9d0a42f.png">

2022-11-27 19:37 UTC, antonilol commented
#1722

2022-11-28 06:10 UTC, mononaut commented
fixes #1722

2022-11-28 07:02 UTC, wiz requested changes
Requested changes:
* Use esplora instead of core RPC, it seems "Get Block Transactions" REST API has the necessary data
* Unrelated to this PR, but also investigate if we can eliminate the `blocks_summaries` table and just query esplora on the fly - would save a lot of disk space and ops indexing time :)

2022-11-28 12:42 UTC, mononaut commented
Updated to use a combination of Core RPC `getBlock(hash, 0)` (raw hex) and fee data from the block summaries database, which is a little faster than fetching verbose blocks from core.

2022-11-29 14:47 UTC, wiz commented on backend/src/api/blocks.ts
> +    if (Common.blocksSummariesIndexingEnabled()) {
This code seems to not work - my `cpfp_clusters` and `transactions` tables are completely empty. Going to disable it for now.
```suggestion
    if (false/*Common.blocksSummariesIndexingEnabled()*/) {
```

2022-11-29 14:57 UTC, wiz approved these changes
Tested ACK @ 272b6d2437f0fe817b954e71def3c12d70ab1a48

* I had to disabled the optimization code path that tries to use the `blocks_summaries` table data if `BLOCKS_SUMMARIES_INDEXING` is enabled - it seems that doesn't work as my `cpfp_clusters` and `transactions` tables don't get populated despite the `cpfp_indexed` bool getting set to true for all blocks?? - it would be nice if the above isssue fixed in the future later on
* Simon also noted that the API request to get audit data will retry in a loop if it gets 404, this should be fixed in a separate PR

2022-11-29 15:05 UTC, merged