toggle to enable/disable block audits
mempool/mempool pull request #2899
Opened 2023-01-03 11:12 UTC by mononaut

Adds a toggle button to the block page to show/hide block audits (if available).

Audits are shown by default, and user's preference is cached to localStorage.

![audit-toggle](https://user-images.githubusercontent.com/83316221/210346352-feea90e8-88aa-4d3d-8a36-a269a40bee00.png)

2023-01-16 05:58 UTC, wiz commented
please rebase

2023-01-16 16:57 UTC, mononaut commented
rebased on current master

2023-01-16 23:11 UTC, softsimon commented
When audit is off, the Block Details button is now too far down from the block dialog.

<img width="167" alt="Screenshot 2023-01-17 at 03 05 16" src="https://user-images.githubusercontent.com/8561090/212777876-7f68a6cb-758d-4662-a22c-9a9e55441a8c.png">

Personally I don't think it looks good enough to see the new audit text and toggle on top of every block page.

May I suggest move it to the bottom, to the left of the details button perhaps. And also even turn the text/toggle into a Bootstrap style toggle button `btn btn-outline-info btn-sm active` when it's enabled. (The details button should also add `active` when it's enabled/expanded

<img width="224" alt="Screenshot 2023-01-17 at 03 10 37" src="https://user-images.githubusercontent.com/8561090/212778375-d37ac55c-20a3-4c9c-ae0b-53361e1518c0.png">

2023-01-26 10:30 UTC, softsimon requested changes
See comment above

2023-01-26 17:13 UTC, mononaut commented
I've pushed an update with those changes:

<img width="363" alt="Screenshot 2023-01-26 at 11 08 50 AM" src="https://user-images.githubusercontent.com/83316221/214903275-a5dbe2e6-f898-4910-9d2f-48fbd43b85e7.png">
<img width="363" alt="Screenshot 2023-01-26 at 11 08 40 AM" src="https://user-images.githubusercontent.com/83316221/214903300-86a14a6d-bce3-4187-9428-5fb9b425cd3b.png">

2023-01-27 08:37 UTC, softsimon approved these changes
tested ACK @ v2.5.0-dev [[714700d8](https://github.com/mempool/mempool/commit/714700d8)]

2023-01-27 08:37 UTC, merged