Fix missing fees in liquid block tooltips
mempool/mempool pull request #3104
Opened 2023-02-22 04:27 UTC by mononaut

Fixes missing fee data in the mined block visualization on Liquid, due to a difference in `getblock` response format between Bitcoin and Elements Core RPC APIs.

| Before | After |
|-|-|
| <img width="513" alt="before-liquid-fees" src="https://user-images.githubusercontent.com/83316221/220521752-5375c9dc-8068-4d92-80e1-9240917dcdc7.png"> | <img width="513" alt="after-liquid-fees" src="https://user-images.githubusercontent.com/83316221/220521766-553144dc-9cea-4eab-99c0-b753289ba171.png"> |

2023-02-23 04:05 UTC, wiz requested changes
Tested NACK @ v2.5.0-dev [[7ab677fe](https://github.com/mempool/mempool/commit/7ab677fe)]

Cleared mempool backend cache, nginx cache, browser cache, but I'm still getting zero fees - any idea?
<img width="468" alt="Screenshot 2023-02-23 at 13 03 35" src="https://user-images.githubusercontent.com/232186/220819044-ad393589-33fe-4ff6-9024-9213fcd5beb5.png">

2023-02-23 16:42 UTC, mononaut commented
I can't reproduce this on [[7ab677fe](https://github.com/mempool/mempool/commit/7ab677fe)].

as far as I can tell I'm running elementsd, esplora, and the mempool backend all with exactly the same config as production, and with the fix my local backend now always serves `/api/v1/block/<hash>/summary` with the correct fees.

<img width="513" alt="Screenshot 2023-02-23 at 9 59 38 AM" src="https://user-images.githubusercontent.com/83316221/220962760-b58d65ea-4a64-4050-a850-05cf02ad31e9.png">

2023-02-23 16:57 UTC, mononaut commented
ok, I think I figured it out.

apparently [fees were only added to the `getblock` response](https://github.com/ElementsProject/elements/commit/658b2312da0ce8a95dc299e08363a2d85be4bd56) from Elements v22 onward, so the data simply isn't available via that method in older versions.

we can either update the minimum supported version to Elements 22.0, or I can rewrite this PR to fetch Liquid tx fees individually from esplora or maybe calculate them explicitly from the transaction data.

2023-02-24 08:13 UTC, wiz commented
ah ok, it's fine, let me upgrade elements on all our servers and I'll re-test this PR

2023-03-18 09:32 UTC, wiz approved these changes
Tested ACK @ v2.5.0-dev [[ed46232b](https://github.com/mempool/mempool/commit/ed46232b)]

2023-03-18 09:32 UTC, softsimon approved these changes
tested ACK @ v2.5.0-dev [ed46232b]

2023-03-18 09:33 UTC, merged