Improve mempool block animations
mempool/mempool pull request #3353
Opened 2023-03-13 09:19 UTC by mononaut

Fixes #672, and slightly refactors the mempool animation logic - mempool blocks now always slide to the right when a new block is mined, except for 'stacks' of multiple mempool blocks which remain stationary on the far left side of the screen.

After:

https://user-images.githubusercontent.com/83316221/224657677-6fd4c4ca-53b4-451c-8474-820d1676e7c2.mov

https://user-images.githubusercontent.com/83316221/224657628-1c2bef49-a9b4-4e84-8a24-28347f1bbdcd.mov

2023-03-13 12:53 UTC, softsimon requested changes
Notes for the record:

* Don't animate the block if the new block happens to be empty, or mostly contain transactions that wasn't expected, eg. was manually added by the miner.

2023-03-14 01:24 UTC, mononaut commented
Updated to not animate if the new block shares <= 50% of transactions by weight with the projected block, using a new "similarity" metric calculated during the block audit.

Liquid, and backends with audits and/or block indexing disabled will continue to animate every block as before.

2023-03-14 05:55 UTC, mononaut commented
Updated to support conditional animation based on mined block similarity even when audits or indexing are disabled.

2023-03-15 07:37 UTC, wiz requested changes
Tested NACK @ 777b30e

```
Mar 15 07:35:39 [98804] DEBUG: <liquid> Exception in runMainUpdateLoop(). Retrying in 5 sec. Reason: Cannot read p
roperties of undefined (reading 'transactions'). Stack trace: TypeError: Cannot read properties of undefined (read
ing 'transactions')
    at Function.getSimilarity (/mempool/liquid/backend/dist/api/common.js:161:41)
    at WebsocketHandler.handleNewBlock (/mempool/liquid/backend/dist/api/websocket-handler.js:460:55)
    at /mempool/liquid/backend/dist/api/blocks.js:540:78
    at Array.map (<anonymous>)
    at Blocks.$updateBlocks (/mempool/liquid/backend/dist/api/blocks.js:540:66)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Server.runMainUpdateLoop (/mempool/liquid/backend/dist/index.js:189:13)
```

2023-03-16 13:19 UTC, mononaut commented
oops, I forgot to handle the case of a completely empty mempool.

It should be fixed now, and rebased on master.

2023-03-18 03:27 UTC, softsimon approved these changes
tested ACK @ v2.5.0-dev [b5c207341]

2023-03-18 03:46 UTC, merged