Global footer
mempool/mempool pull request #3564
Opened 2023-03-24 09:17 UTC by softsimon

The footer is now global at the bottom on all pages, except the About page.

2023-03-24 12:26 UTC, bufo24 commented on frontend/src/app/components/master-page/master-page.component.ts
> +      console.log(paths);
Remove logging
```suggestion
```

2023-03-31 06:47 UTC, hunicus reviewed
This will be very helpful to have for #3446.

Some findings...

Footer can appear to the side of the sidebar for docs on desktop when window:

![Screenshot from 2023-03-31 01-30-43](https://user-images.githubusercontent.com/93150691/229031951-17c65fc0-f681-40e1-ab20-6e0db742b5ef.png)

Footer is not on about page:

![Screenshot from 2023-03-31 01-31-10](https://user-images.githubusercontent.com/93150691/229031957-11ccf870-3a20-4b98-aa31-aee54d23001b.png)

Footer clashes with bottom of docs page on mobile:

![Screenshot from 2023-03-31 02-44-36](https://user-images.githubusercontent.com/93150691/229044188-9dbdefd6-be6f-4386-8026-960afa424ab8.png)

2023-04-03 13:27 UTC, wiz requested changes
Missing footer on liquid pages

2023-05-04 16:30 UTC, hunicus commented
It looks like the footer isn't working on the Liquid site because of an unrelated error in `asset-circulation.component.ts` that occurs before the changes in this pull request.

How can we proceed?

2023-05-04 22:13 UTC, hunicus approved these changes
ACK @ https://github.com/mempool/mempool/pull/3564/commits/4c5ece82491b1df880e591fe0479338e754cf9fb

2023-05-04 22:14 UTC, merged