Adds SSL to config
mempool/mempool pull request #3756
Opened 2023-05-11 21:07 UTC by ProgramComputer

Adds SSL to config. #2840

2023-05-14 21:32 UTC, knorrium commented
@ProgramComputer heads up that I'm adding tests for the Docker config and you'll have to rebase once #3776 gets merged. Sorry for the inconvenience.

2023-05-26 15:43 UTC, knorrium commented
@ProgramComputer we merged the other PR, can you please fix the merge conflicts so the new tests can run?

2023-05-26 16:39 UTC, ProgramComputer commented
> @ProgramComputer we merged the other PR, can you please fix the merge conflicts so the new tests can run?

Merge conflicts fixed

2024-02-22 06:50 UTC, wiz commented
Thanks for the PR, but could you default to SSL = false?
Since this is something new it should not be enabled by default

2024-02-22 09:09 UTC, ProgramComputer commented
> Thanks for the PR, but could you default to SSL = false? Since this is something new it should not be enabled by default

Changed the SSL default to false

2024-02-22 16:34 UTC, softsimon requested changes

2024-02-22 16:34 UTC, softsimon commented on production/mempool-config.testnet.json
> +    "SSL":false
You can revert all production config additions, as we don't need to add when the default config is the same. Keeps them cleaner.

2024-04-09 11:22 UTC, closed without merging