Add average fee delta to pool ranking
mempool/mempool pull request #3919
Opened 2023-07-03 14:49 UTC by joostjager

This PR is an extension to https://github.com/mempool/mempool/pull/3846 to show the average fee delta per pool in the pool ranking overview. It is a small change that doesn't involve a database migration or new strings to translate, but arguably adds the most telling block fee audit-based statistic.

![image](https://github.com/mempool/mempool/assets/4638168/b5dbcefa-1620-4a13-9646-f8d9d009e615)

2023-07-03 22:15 UTC, mononaut requested changes
Concept ACK

I've suggested some changes to fix layout issues on smaller screens.

2023-07-03 22:15 UTC, mononaut commented on frontend/src/app/components/pool-ranking/pool-ranking.component.html
>            <th class="d-none d-md-table-cell" i18n="mining.empty-blocks">Empty blocks</th>
```suggestion
          <th *ngIf="auditAvailable" class="d-none d-sm-table-cell" i18n="mining.fees-per-block">Avg Block Fees</th>
          <th class="d-none d-lg-table-cell" i18n="mining.empty-blocks">Empty blocks</th>
```

2023-07-03 22:15 UTC, mononaut commented on frontend/src/app/components/pool-ranking/pool-ranking.component.html
> +          <td *ngIf="auditAvailable" class="d-flex justify-content-center">
```suggestion
          <td *ngIf="auditAvailable" class="d-none d-sm-table-cell">
```

2023-07-03 22:15 UTC, mononaut commented on frontend/src/app/components/pool-ranking/pool-ranking.component.html
>            <td class="d-none d-md-table-cell">{{ pool.emptyBlocks }} ({{ pool.emptyBlockRatio }}%)</td>
```suggestion
          <td class="d-none d-lg-table-cell">{{ pool.emptyBlocks }} ({{ pool.emptyBlockRatio }}%)</td>
```

2023-07-04 11:29 UTC, joostjager commented
@mononaut thanks. Squashed the commits and added `Co-authored-by` to not introduce unnecessary diff between commits.

2023-07-04 14:38 UTC, mononaut approved these changes
Tested ACK @ [9e5d10b1]

2023-07-05 13:25 UTC, softsimon reviewed
EDIT..

2023-07-05 13:30 UTC, merged

2023-07-05 15:08 UTC, joostjager commented
@softsimon, I'd not expect the query to be meaningfully slower given that no new joins are made. But I can only guess as to why you editted 'EDIT..' 😅 

EIther way, thanks for accepting the change!