Replace client-side stale blocks
mempool/mempool pull request #3937
Opened 2023-07-10 05:05 UTC by mononaut

_(builds on PR #3932)_

This PR refactors the frontend `stateService.blocks$` observable so that we can swap out the client-side cached blocks when a reorg occurs and always show the latest main chain data.

https://github.com/mempool/mempool/assets/83316221/cac77695-c3e6-4475-ae0f-13b7fe89e8bf

2023-07-11 05:50 UTC, mononaut commented
rebased

2023-07-11 06:55 UTC, softsimon commented on frontend/src/app/components/block/block.component.ts
> +          } else if (block.height === this.block.height) {
Getting the following error when clicking on a block from the dashboard, or simply loading the dashboard

`ERROR TypeError: Cannot read properties of undefined (reading 'height')`

2023-07-11 06:55 UTC, softsimon commented on frontend/src/app/components/blockchain-blocks/blockchain-blocks.component.ts
> +    const blockindex = this.blocks.findIndex((b) => { console.log(b); return b.height === this.markHeight });
Remove `console.log`

2023-07-11 07:35 UTC, mononaut commented
pushed a fix

2023-07-12 03:16 UTC, softsimon requested changes
If a stale block push appears, you click somewhere else and go back, the banner is gone.

2023-07-12 07:26 UTC, mononaut commented
should be fixed now

2023-07-13 01:41 UTC, softsimon commented
Please rebase.

2023-07-13 02:06 UTC, mononaut commented
rebased

2023-07-13 02:43 UTC, softsimon approved these changes
tested ACK @ [1e69ea2]

2023-07-13 03:08 UTC, merged