Faster blocks
mempool/mempool pull request #4045
Opened 2023-07-24 08:27 UTC by mononaut

_(builds on PR #4025)_

This PR uses a new `/block/:hash/txs` endpoint added in https://github.com/mempool/electrs/pull/24 to speed up block processing by loading block transactions in a single request instead of individually.

2023-07-24 11:24 UTC, wiz approved these changes
Tested ACK @ d35d04b2e82f134f90ae2875d368326a2b7a5585

2023-07-24 11:28 UTC, softsimon requested changes
We must use the existing mempool transactions on new block

2023-07-24 15:26 UTC, softsimon requested changes
The fee spans are now gone

<img width="652" alt="Screenshot 2023-07-25 at 00 26 02" src="https://github.com/mempool/mempool/assets/8561090/c736c13f-9acc-4206-91cf-657895503fc8">

2023-07-25 03:16 UTC, mononaut commented
Rebased on master, and refactored the `$getTransactionsExtended` function as follows:
 - try to look up transactions in the mempool cache first.
 - if esplora is enabled and we still need to fetch > 500 transactions, fetch them in bulk using the new mempool/electrs endpoint.
 - fetch any remaining missing transactions individually.
 
The other logic should be unchanged, except that I've removed the `memPool.hasPriority()` short-circuit on non-esplora backends. With the more conservative inSync behavior from #4043 the mempool always has priority while resyncing the last `INITIAL_BLOCKS_AMOUNT` blocks, so the short-circuit just wrecks those block templates.

2023-07-25 05:08 UTC, softsimon approved these changes
tested ACK @ [25925751e]

2023-07-25 07:07 UTC, merged