use bulk /txs endpoint to check cached rbf tx status
mempool/mempool pull request #4101
Opened 2023-08-05 07:55 UTC by mononaut

After we load RBF data in from the cache, we need to check if anything got mined or removed from the mempool while we were offline.

Currently, we fetch these transactions one by one, but that can be slow when there are a lot of transactions in the RBF cache.

This PR uses a new esplora /txs endpoint to fetch the transactions in bulk, which speeds up the process significantly.

(we can't use the `/mempool/txs` esplora endpoint because we need differentiate between transactions being confirmed and evicted from the mempool)

2023-08-06 05:24 UTC, softsimon requested changes

2023-08-06 05:24 UTC, softsimon commented on backend/src/api/bitcoin/esplora-api.ts
> +    return this.$postWrapper<IEsploraApi.Transaction[]>(config.ESPLORA.REST_API_URL + '/txs', txids, 'json');
Endpoint doesn't exist ,, `/mempool` is missing?

2023-08-06 05:26 UTC, softsimon commented
Requires https://github.com/mempool/electrs/pull/33

2023-11-12 06:20 UTC, mononaut commented
re-rebased on #4158

2023-11-12 10:09 UTC, wiz approved these changes
Tested ACK with requested changes @ 5998b54

Seems to mostly work with 1000 chunk size, but still fails occasionally so let's merge using 250 chunk size and see how it goes

```
Nov 12 10:03:18 [51122] DEBUG: RUST makeBlockTemplates completed in 13.296 seconds
Nov 12 10:03:26 [51122] INFO: Restoring rbf data from disk cache
Nov 12 10:03:28 [51122] INFO: Starting statistics service
Nov 12 10:03:28 [51122] DEBUG: [Mining] Inserted 0 MtGox USD weekly price history into db
Nov 12 10:03:29 [51122] DEBUG: [Mining] Fetching daily price history from exchanges and saving missing ones into the database
Nov 12 10:03:29 [51122] DEBUG: Updated orphaned blocks cache. Found 6 orphaned blocks
Nov 12 10:03:29 [51122] NOTICE: Mempool Server is running on port 8999
Nov 12 10:03:30 [51122] DEBUG: [Mining] Inserted 0 daily historical prices into the db
Nov 12 10:03:30 [51122] DEBUG: [Mining] Fetching hourly price history from exchanges and saving missing ones into the database
Nov 12 10:03:31 [51122] DEBUG: [Mining] Inserted 0 hourly historical prices into the db
Nov 12 10:03:32 [51122] DEBUG: Memory usage: 4.40 GB / 16.05 GB
Nov 12 10:03:38 [51122] WARN: esplora request failed undefined /bitcoin/socket/esplora-bitcoin-mainnet/internal/txs
Nov 12 10:03:38 [51122] WARN: timeout of 10000ms exceeded
Nov 12 10:03:38 [51122] ERR: failed to fetch or process 1000 cached rbf transactions
Nov 12 10:03:39 [51122] WARN: esplora request failed undefined /bitcoin/socket/esplora-bitcoin-mainnet/mempool/txids
Nov 12 10:03:39 [51122] WARN: timeout of 10000ms exceeded
Nov 12 10:03:39 [51122] DEBUG: Exception in runMainUpdateLoop() (count: 1). Retrying in 1 sec. Reason: timeout of 10000ms exceeded. Stack trace: AxiosError: timeout of 10000ms exceeded
    at RedirectableRequest.handleRequestTimeout (/mempool/mainnet/backend/node_modules/axios/dist/node/axios.cjs:3120:16)
    at RedirectableRequest.emit (node:events:514:28)
    at Timeout.<anonymous> (/mempool/mainnet/backend/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Nov 12 10:03:39 [51122] DEBUG: AxiosError: timeout of 10000ms exceeded
Nov 12 10:03:48 [51122] DEBUG: Initial difficulty adjustment data set.
Nov 12 10:03:48 [51122] DEBUG: New block found (#816428)!
Nov 12 10:03:48 [51122] WARN: esplora request failed undefined /bitcoin/socket/esplora-bitcoin-mainnet/internal/txs
Nov 12 10:03:48 [51122] WARN: timeout of 10000ms exceeded
Nov 12 10:03:48 [51122] ERR: failed to fetch or process 1000 cached rbf transactions
Nov 12 10:03:49 [51122] DEBUG: Updated orphaned blocks cache. Found 6 orphaned blocks
Nov 12 10:03:53 [51122] DEBUG: 907 of 4832 found in mempool. 3925 fetched through backend service.
Nov 12 10:03:53 [51122] DEBUG: 0 websocket clients | 0 connected | 0 disconnected | (+0)
Nov 12 10:03:55 [51122] DEBUG: RUST updateBlockTemplates completed in 2.03 seconds
Nov 12 10:03:55 [51122] DEBUG: New block found (#816429)!
Nov 12 10:03:56 [51122] DEBUG: Updated orphaned blocks cache. Found 6 orphaned blocks
Nov 12 10:03:56 [51122] DEBUG: fetched 1000 cached rbf transactions
Nov 12 10:03:56 [51122] DEBUG: processed 1000 cached rbf transactions
Nov 12 10:03:56 [51122] DEBUG: fetched 1000 cached rbf transactions
Nov 12 10:03:56 [51122] DEBUG: processed 1000 cached rbf transactions
Nov 12 10:04:04 [51122] DEBUG: fetched 1000 cached rbf transactions
Nov 12 10:04:04 [51122] DEBUG: processed 1000 cached rbf transactions
Nov 12 10:04:10 [51122] DEBUG: 3271 of 5121 found in mempool. 1850 fetched through backend service.
Nov 12 10:04:11 [51122] DEBUG: fetched 1000 cached rbf transactions
Nov 12 10:04:11 [51122] DEBUG: processed 1000 cached rbf transactions
Nov 12 10:04:11 [51122] DEBUG: 0 websocket clients | 0 connected | 0 disconnected | (+0)
Nov 12 10:04:13 [51122] DEBUG: RUST updateBlockTemplates completed in 1.826 seconds
```

2023-11-12 10:09 UTC, wiz commented on backend/src/api/rbf-cache.ts
> +      const sliceLength = 1000;
```suggestion
      const sliceLength = 250;
```

2023-11-12 10:10 UTC, merged