Nginx: Ignore all internal-api paths
mempool/mempool pull request #4158
Opened 2023-08-16 07:47 UTC by junderw

TODO: Cleanup these new intensive endpoints that have been added recently.

- [ ] Remove the endpoints from the backend so they are not exposed to the frontend.
- [ ] Ensure that only the backend can access the mempool-electrs.

2023-08-16 07:49 UTC, junderw commented
@mononaut Please assist if you have time.

@wiz Nginx is not my forte, if you have any comments I'd appreciate it.

Since we only need a lot of these new mempool-electrs endpoints for the backend, we should only allow the backend to access these endpoints.

2023-08-27 16:20 UTC, wiz requested changes
NACK for URL schema and nginx configuration, see suggested changes and also please add i.e. `/testnet/api/internal` and `/testnet/api/v1/internal` in `location-testnet-api.conf` and similar for signet, liquid, liquidtestnet, and bisq routing as well

2023-08-27 16:20 UTC, wiz commented on backend/src/api/bitcoin/esplora-api.ts
> +    return this.failoverRouter.$post<IEsploraApi.Transaction[]>('/internal-api/mempool/txs', txids, 'json');
```suggestion
    return this.failoverRouter.$post<IEsploraApi.Transaction[]>('/internal/mempool/txs', txids, 'json');
```

2023-08-27 16:20 UTC, wiz commented on backend/src/api/bitcoin/esplora-api.ts
> +    return this.failoverRouter.$get<IEsploraApi.Transaction[]>('/internal-api/mempool/txs' + (lastSeenTxid ? '/' + lastSeenTxid : ''));
```suggestion
    return this.failoverRouter.$get<IEsploraApi.Transaction[]>('/internal/mempool/txs' + (lastSeenTxid ? '/' + lastSeenTxid : ''));
```

2023-08-27 16:20 UTC, wiz commented on nginx-mempool.conf
> +
```suggestion
```

2023-08-27 16:20 UTC, wiz commented on production/nginx/location-api.conf
> +
```suggestion
location /api/internal/ {
	return 404;
}
location /api/v1/internal/ {
	return 404;
}
```

2023-08-27 17:29 UTC, junderw commented
Merged suggestions and added 404 endpoints to each conf file with their respective root paths.

2023-11-12 05:15 UTC, mononaut commented
rebased on current master [1e69f3b3]

2023-11-12 08:39 UTC, wiz approved these changes
Tested ACK @ v3.0.0-dev [ee90a96d2]

2023-11-12 08:40 UTC, merged