Make search and select work for truncated text
mempool/mempool pull request #4368
Opened 2023-11-13 08:46 UTC by softsimon

fixes #4367

With this solution of a hidden transparent text, search and find is possible on transaction and address page for example.

Tried on Chrome, Firefox and Safari.

<img width="1436" alt="Screenshot 2023-11-13 at 17 43 39" src="https://github.com/mempool/mempool/assets/8561090/19c73e68-6e83-4e3d-afa8-ff22fd2b8bc7">

2023-11-14 10:08 UTC, nymkappa requested changes
Seems to be working fine overall. But tested NACK because it creates an overflow on mobile layout when checking an address.

<img width="403" alt="image" src="https://github.com/mempool/mempool/assets/9780671/ce033813-0954-4a34-a5c0-889bccd223f2">

2023-11-15 06:12 UTC, softsimon commented
> Seems to be working fine overall. But tested NACK because it creates an overflow on mobile layout when checking a transaction.

Should be fixed now.

2023-11-15 06:55 UTC, nymkappa commented
Tested ACK @ 86fe6a802b2bb069cd32bdb62f079fad961e90de

Next improvement would be to be able to search through the whole list of input/outputs which are hidden by default.

<img width="556" alt="image" src="https://github.com/mempool/mempool/assets/9780671/8e88590b-b887-493e-a164-663c84f8868a">

2023-11-15 06:56 UTC, nymkappa approved these changes
Tested ACK @ 86fe6a802b2bb069cd32bdb62f079fad961e90de

Next improvement would be to be able to search through the whole list of input/outputs which are hidden by default.

<img width="556" alt="image" src="https://github.com/mempool/mempool/assets/9780671/8e88590b-b887-493e-a164-663c84f8868a">

2023-11-15 07:25 UTC, merged