Search result: do not offer "Go to" if block height > chain tip
mempool/mempool pull request #4502
Opened 2023-12-13 18:33 UTC by natsee

Fixes #4474 

<img width="497" alt="Screenshot 2023-12-13 at 19 24 25" src="https://github.com/mempool/mempool/assets/46578910/88f695a8-5bb9-4c4b-9c1c-1c3bd8e32ddc">

2023-12-14 02:16 UTC, softsimon commented on frontend/src/app/components/search-form/search-results/search-results.component.html
> +  <ng-template #noBlockFound [ngIf]="results.blockHeight && results.blockHeightOutOfRange">
We can remove this part.

We never show "Lightning Channel not found" or similar when posting wrong info ... We just display what it matches.

2023-12-14 07:51 UTC, softsimon requested changes
See comment

2023-12-14 08:42 UTC, natsee commented
Removed the "No block found" message:

<img width="502" alt="Screenshot 2023-12-14 at 09 42 20" src="https://github.com/mempool/mempool/assets/46578910/3ad0a1a7-fb85-460c-aca9-fbbef11158d0">

2023-12-14 09:28 UTC, softsimon requested changes
I realized we don't need the `blockHeightOutOfRange` stuff anymore.. just adding this to the existing matchesBlockHeight check.


`const matchesBlockHeight = this.regexBlockheight.test(searchText) && parseInt(searchText) <= this.stateService.latestBlockHeight;`

2023-12-17 03:50 UTC, softsimon approved these changes
tested ACK @ [b0c02b16]

2023-12-17 03:50 UTC, merged