Fix pools dominance chart
mempool/mempool pull request #4626
Opened 2024-01-27 22:18 UTC by mononaut

This PR fixes the pools dominance chart, which is currently broken when any pools mined blocks in some periods but not others.

Before:
<img width="1062" alt="Screenshot 2024-01-27 at 10 13 31 PM" src="https://github.com/mempool/mempool/assets/83316221/d4a9dc69-d4e5-49c0-8363-8c8cd506276c">

After:
<img width="1062" alt="Screenshot 2024-01-27 at 10 13 04 PM" src="https://github.com/mempool/mempool/assets/83316221/9258b318-8eb2-4026-8051-e3dec57832d2">

2024-01-28 08:49 UTC, nymkappa requested changes
I don't have this bug locally, so I guess that's what you mean by "explicitly sorts pools", the result can have some randomness?

I think the new ordering is not good either. What we should aim for is keeping the color (the ordering) consistent between all timespan. I think that's how I was doing it before, ordering by their latest weekly hashrate share.

With your PR, Foundry is red on the 6m chart and at the bottom, but on the all timespan, it becomes light blue and is moved in the middle of the chart, making it very hard to track things.

<img width="1430" alt="Screenshot 2024-01-28 at 09 42 14" src="https://github.com/mempool/mempool/assets/9780671/0bad19fc-c0dd-4ada-9c59-bd02335bde85">

<img width="1435" alt="Screenshot 2024-01-28 at 09 42 22" src="https://github.com/mempool/mempool/assets/9780671/df213578-cf64-4ba2-b574-bc277577867a">

2024-01-28 22:32 UTC, mononaut commented
This PR sorts by average % hashrate over the whole chart, but yeah I'll switch to sorting by % hashrate in the most recent data point so the ordering/colors are stable across different timespans (although we'll need some sort of stable tie-breaker for pools with equal/zero hashrate in the latest point).

2024-01-29 06:11 UTC, nymkappa commented
Just go with a good old alphanumeric tie break hehe

2024-01-29 19:48 UTC, mononaut commented
Updated with stable sorting

2024-01-30 10:19 UTC, nymkappa approved these changes
Tested ACK @ 2637636f27306e5a1d55d0600cb54a72bfbcec18

2024-01-30 10:21 UTC, merged