Show accelerator audit total on block page
mempool/mempool pull request #4736
Opened 2024-03-05 00:55 UTC by mononaut

This PR makes use of some of the new locally audited acceleration info APIs added in #4718 to display any additional out-of-band fees on the block page:

<img width="422" alt="Screenshot 2024-03-05 at 12 52 54 AM" src="https://github.com/mempool/mempool/assets/83316221/f5fea5fa-abe5-4c68-be19-6a2e27a1567b">

2024-03-05 11:16 UTC, wiz commented
Concept ACK - is this ready for review?

2024-03-05 22:08 UTC, mononaut commented
yes, ready for review.

I'm not 100% sure this is the best way to display this data, but we can iterate.

2024-03-06 07:19 UTC, softsimon requested changes
The call for accelerations on the block page needs to be limited to prod with services backend.

2024-03-06 07:25 UTC, wiz commented
Right, it should be using the backend-configured hostname which defaults to mempool.space
Also, it needs to respect if the accelerator feature is disabled

2024-03-06 07:28 UTC, wiz commented
And it seems a test is failing

2024-03-06 20:25 UTC, mononaut commented
The purpose of this is to showcase the new open-source calculation/audit of acceleration fees, so it doesn't rely on the services API, and should work on any instance where `config.MEMPOOL_SERVICES` is properly configured to fetch public acceleration data from mempool.space.

If that's disabled on the backend, then those new APIs return `[]` and nothing is displayed on the frontend.

But yeah maybe we should add a new frontend config setting to enable/disable local non-services acceleration features (like this, highlighting accelerations in the block visualizations, etc), separate from the acceleration dashboard and official accelerator stuff.

2024-03-07 20:04 UTC, mononaut commented
fixed

2024-03-09 04:52 UTC, wiz approved these changes
utACK

2024-03-09 04:52 UTC, merged