Display basic mining info on transaction page
mempool/mempool pull request #4748
Opened 2024-03-07 23:55 UTC by mononaut

This PR is a partial implementation of the feature described in #4422.

It adds a new "mining" row to the details panel on the transaction page, which includes a miner tag and (if available) some other audit-related status badges.

This feature is only enabled on Bitcoin mainnet, and the audit-related functionality is further restricted to instances with the `AUDIT` and `MINING_DASHBOARD` settings enabled, and for blocks above the `MAINNET_BLOCK_AUDIT_START_HEIGHT`.

The audit-related badges all have mouse-over tooltips with more information.

<img width="1021" alt="Screenshot 2024-03-07 at 11 36 41 PM" src="https://github.com/mempool/mempool/assets/83316221/08c95cf7-0c75-4292-bf6f-59e94a1259e7">
<img width="1021" alt="Screenshot 2024-03-07 at 11 34 40 PM" src="https://github.com/mempool/mempool/assets/83316221/a6b481d8-7621-4d8a-9b96-1fa802550f26">
<img width="1021" alt="Screenshot 2024-03-07 at 11 35 30 PM" src="https://github.com/mempool/mempool/assets/83316221/99b93405-c6c6-427c-8933-1a907fc3abac">
<img width="1021" alt="Screenshot 2024-03-07 at 11 34 26 PM" src="https://github.com/mempool/mempool/assets/83316221/c8e313bc-3527-4076-816e-72c81a396ccf">

The audit status badges aren't an exact match for the functionality in #4422. Specifically:
 - No "Delayed" badge, since we don't currently have a good way to identify that case.
 - The "(Not) Seen in mempool" and "Added" badges have slightly different semantics:
    - "Added" matches the current usage in the block audit (either added out-of-band, or intentionally prioritized)
    - "Seen in mempool" is displayed if the transaction is neither "added" nor a "conflict", and the "Expected in Block" badge is not already displayed. This more or less matches the "Marginal fee rate" badge in the main block audit.
        - Since we don't currently record whether transactions were seen in the mempool or not, this is necessarily a bad heuristic.
 - Additional "Conflict" badge, with the same meaning as the main block audit.

When we overhaul the main block audit feature to disambiguate some of these cases, we can update these tags on the transaction page at the same time.

2024-03-08 07:41 UTC, orangesurf commented
utACK 

The logic makes sense and the tooltips are clear.

2024-03-08 07:50 UTC, orangesurf approved these changes
utACK
The logic makes sense and the tooltips are clear.

2024-03-08 09:31 UTC, nymkappa commented
<img width="499" alt="image" src="https://github.com/mempool/mempool/assets/9780671/b158337d-078e-44a0-8218-b8d311bee229">

2024-03-08 09:34 UTC, nymkappa commented
Also I'm confused about badges between the `Recently broadcasted` and `Marginal fee rate` status, but could be my lack of understanding about the audit status.

- A `Recently broadcasted` tx shows `Expected in Block` badge
- A `Marginal fee rate` tx shows `Seen in Mempool` badge

What's the difference ?

2024-03-08 12:40 UTC, wiz requested changes
![Screenshot 2024-03-08 at 21 38 04](https://github.com/mempool/mempool/assets/232186/93daf758-cb72-4a65-8fa9-1709f97e7a86)

2024-03-08 15:12 UTC, mononaut commented
> Also I'm confused about badges between the `Recently broadcasted` and `Marginal fee rate` status, but could be my lack of understanding about the audit status.
> 
> * A `Recently broadcasted` tx shows `Expected in Block` badge
> * A `Marginal fee rate` tx shows `Seen in Mempool` badge
> 
> What's the difference ? Even though a tx has a marginal fee rate, we could assume it was expected in the block right. It just happen that our algo did not include it in our block template while the miner did (for whatever reason).

"Recently broadcasted" is a status applied to transactions in the *projected template*, so it doesn't directly correspond to anything here (the "Expected in Block" badge you're seeing is from a later block where the transactions *was* mined)

"Marginal fee rate" implies "Seen in Mempool", because our current audit system applies that status when a transaction is missing from the projected template (so not "Expected in Block"), but *was* somewhere in the second projected mempool block. We don't currently track which transactions we did or didn't see in the mempool beyond the second block, so this is the best we can do for now.

Similarly, some of the "Added" transactions may actually have been in the mempool, we just can't tell which with the data currently available.

2024-03-08 15:23 UTC, mononaut commented
Fixed

<img width="564" alt="Screenshot 2024-03-08 at 3 23 37 PM" src="https://github.com/mempool/mempool/assets/83316221/602d322d-9b03-41ad-bdca-3452db604b85">

2024-03-08 22:48 UTC, nymkappa commented
> "Recently broadcasted" is a status applied to transactions......we just can't tell which with the data currently available.

Thanks. I just noticed we actually have a FAQ for that. Clicking on those badge should point to it 🙏 so I can get out of the noob zone.

2024-03-09 04:50 UTC, wiz approved these changes
utACK (based on previous test)

2024-03-09 04:50 UTC, merged