Refactor block transactions
mempool/mempool pull request #5085
Opened 2024-05-18 17:45 UTC by softsimon

What this PR / Refactor does:

1. The Transactions list on the Block page is now it's own separate component reducing the complexity of Block component slightly.
2. The new Angular defer view feature is utilized. So only when the Transactions list on the block page is visible in the viewport, it will render and load the transactions saving rendering time and server traffic, that commonly isn't required as mobile phones need to scroll down to view transactions. As soon as the transactions list is in view, the old behaviour of loading the transactions and lazy-loading the previous block kicks in, so people with long screens shouldn't notice any difference.

2024-05-19 06:22 UTC, softsimon commented
Ok, of course tests fail now when them expect the block transactions list to be loaded even if it's outside of the cypress test view.

2024-05-20 20:46 UTC, mononaut requested changes
Concept ACK: the deferred load is a good idea, and this implementation works well.

I just have a few minor comments below to resolve.

2024-05-20 20:46 UTC, mononaut commented on frontend/src/app/components/block/block-transactions.component.ts
> +    );
this whole section feels a little out-of-place in the new component.

I wonder if we could:
 - just grab the block reward directly from the `BlockExtended` object in the main block component, if we need it there?
 - move the next block transactions preloading stuff either back to the main block component or offload it to a service or something?

2024-05-20 20:46 UTC, mononaut commented on frontend/src/app/components/block/block-transactions.component.ts
> +          startWith(null),
this `startWith(null)` causes the `tap` block below to trigger twice on load (first with null, then again with the actual transactions when the API call returns), which means we end up making duplicate requests to `getBlockTransactions$(...)`.

2024-05-22 15:35 UTC, mononaut approved these changes
Tested ACK @ [ea0a4d1d67a41f31eb93e284c0a1fe860a5dcd75]

2024-05-22 15:36 UTC, merged