Multi-pool ETA
mempool/mempool pull request #5120
Opened 2024-05-30 21:44 UTC by mononaut

This PR improves the ETA calculation for transactions being accelerated by multiple different pools.

<img width="897" alt="Screenshot 2024-05-30 at 9 28 07 PM" src="https://github.com/mempool/mempool/assets/83316221/960be491-78a8-45b8-9c3d-1a59df86cb0a">

It leverages the "approximate accelerated position" calculations from closed PR #4642 to figure out which projected mempool block the transaction lies in for each subset of global hashrate, and then calculates the expected time until confirmation as follows:

#### ETA Calculation
let
  - $H(n)$ be the proportion of hashrate for which the transaction is in mempool block ≤ $n$
  - $S(n)$ be the probability of the transaction being mined in block $n$
    - by definition, $S(max) = 1$ , where $max$ is the maximum depth of the transaction in any mempool, and therefore $S(n>max) = 0$, so we only need to calculate $max$ different values.
  - $Q$ be the expected number of blocks until the transaction is confirmed.
  - $E$ be the expected time until the transaction is confirmed.

then
  - $S(0) = H(0)$
  - $S(i) = H(i) \times (1 - \sum\limits_{j=0}^{i-1} S(j))$
    - the probability of mining a block including the transaction at this depth, multiplied by the probability that it hasn't already been mined at an earlier depth.
  - $Q = \sum\limits_{i=0}^{max} S(i) \times (i+1)$
    - number of blocks, weighted by the probability that the block includes the transaction
  - $E = Q \times T$
    - expected number of blocks, multiplied by the avg time per block

2024-06-04 06:05 UTC, wiz requested changes
Tests fail for dev build
```
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
FAIL src/__tests__/api/difficulty-adjustment.test.ts
  ● Test suite failed to run

    Jest worker encountered 4 child process exceptions, exceeding retry limit

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)

/home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946
            logger_1.default[errorLogLevel](`database query "${
                                           ^

TypeError: logger_1.default[errorLogLevel] is not a function
    at /home/runner/work/mempool/mempool/21/dev/backend/src/database.ts:3946:44
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.7.3
FAIL src/__tests__/api/common.ts
  ● Test suite failed to run

    Jest worker encountered 4 child process exceptions, exceeding retry limit

      at ChildProcessWorker.initialize (node_modules/jest-worker/build/workers/ChildProcessWorker.js:181:21)
      ```

2024-06-04 21:01 UTC, mononaut commented
rebased & fixed failing tests

2024-06-05 05:21 UTC, wiz approved these changes
utACK

2024-06-05 05:21 UTC, merged

2024-06-12 01:21 UTC, beage666 commented on frontend/src/app/services/state.service.ts
> +  accelerationPositions?: AccelerationPosition[];
Is up running