Invert graph legends order.
mempool/mempool pull request #532
Opened 2021-05-20 18:53 UTC by MiguelMedeiros

Fix #507 .
## /graphs
![image](https://user-images.githubusercontent.com/5798170/119033238-6158dc80-b983-11eb-8f8e-693f196d8e44.png)

## /tv
![image](https://user-images.githubusercontent.com/5798170/119033265-687fea80-b983-11eb-9576-5cfd14e4c556.png)

2021-05-21 11:01 UTC, softsimon commented
Some people are using the graph in a flipped orientation. So the legends should flip to the same orientation as the localStorage `inverted-graph` setting.

<img width="45" alt="Screen Shot 2021-05-21 at 15 00 23" src="https://user-images.githubusercontent.com/8561090/119127353-477fce00-ba45-11eb-95cd-c34066ba69ee.png">

2021-05-21 11:02 UTC, softsimon requested changes
Some people are using the graph in a flipped orientation. So the legends should flip to the same orientation as the localStorage `inverted-graph` setting.

<img width="45" alt="Screen Shot 2021-05-21 at 15 00 23" src="https://user-images.githubusercontent.com/8561090/119127353-477fce00-ba45-11eb-95cd-c34066ba69ee.png">

2021-05-21 15:30 UTC, MiguelMedeiros commented
> Some people are using the graph in a flipped orientation. So the legends should flip to the same orientation as the localStorage `inverted-graph` setting.
> 
> <img alt="Screen Shot 2021-05-21 at 15 00 23" width="45" src="https://user-images.githubusercontent.com/8561090/119127353-477fce00-ba45-11eb-95cd-c34066ba69ee.png">

@softsimon can you test it for me?

2021-05-23 09:51 UTC, softsimon approved these changes

2021-05-23 09:51 UTC, merged