Fix address balance graph
mempool/mempool pull request #5654
Opened 2024-11-19 17:16 UTC by natsoni

Fixes #5647
Fixes #5648 

Fixes the overflow USD amount y axis with some languages.
Before: 

<img width="107" alt="Screenshot 2024-11-19 at 18 15 53" src="https://github.com/user-attachments/assets/ef9bad38-b1dc-495f-b6e0-a645b0ba97b6">

After: 

<img width="93" alt="Screenshot 2024-11-19 at 18 16 06" src="https://github.com/user-attachments/assets/4bc5b528-4f33-4ade-9cda-98f7377e4e2a">

2024-11-19 17:18 UTC, nymkappa commented
Can you check if it also fixes this one? https://github.com/mempool/mempool/issues/5498

2024-11-19 18:33 UTC, natsoni commented
> Can you check if it also fixes this one? #5498

[cb3326d](https://github.com/mempool/mempool/pull/5654/commits/cb3326d6917344ecf2999ebd95ac86d097df16eb) should fix it but I can't find a test case 😁

2024-11-22 09:59 UTC, nymkappa approved these changes
Tested ACK @ cb3326d6917344ecf2999ebd95ac86d097df16eb

Fixes https://github.com/mempool/mempool/issues/5498

2024-11-22 10:06 UTC, nymkappa requested changes
Looks good for the chart axis, but the tooltip needs more polish

- [ ] Date is not in white color
- [ ] Date is not left aligned
- [ ] It's missing the chart legend color

### Polished tooltip should look like the following
(without the "around block" ofc)
![Screenshot 2024-11-22 at 11 03 44](https://github.com/user-attachments/assets/ffcbc0f2-5d0e-4777-aa0b-e896c82fa2a8)

### but in the "worst case scenario" it looks like this

![Screenshot 2024-11-22 at 11 03 32](https://github.com/user-attachments/assets/00ed0243-e1dd-4f9f-be4c-ad9c998e0514)

2024-12-06 08:13 UTC, wiz commented
@nymkappa is this PR ok to merge as-is and fix that stuff in a separate PR ?

2024-12-06 08:15 UTC, nymkappa commented
> @nymkappa is this PR ok to merge as-is and fix that stuff in a separate PR ?

yes, only the tooltip needs polish

2024-12-06 08:17 UTC, merged