Liquid: Display unconfidential address and fix tracking
mempool/mempool pull request #768
Opened 2021-09-06 06:21 UTC by softsimon

fixes #761

Loading a liquid confidential address like: lq1qqgddwun5n54jq8za4rkddalngqtcc6skcelg7mquc40ayscr285ksaxs3a72pf6knc4zrx7pk7ggwueu0lkdw009cvvwhqel2

It will now look like this, and tracking should now work since the unconfidential address is used.

<img width="624" alt="Screen Shot 2021-09-06 at 10 18 30" src="https://user-images.githubusercontent.com/8561090/132169636-de7c7df5-97fc-47ef-bd0f-bafa73a7dbef.png">

2021-09-06 21:34 UTC, wiz requested changes
1) Regex fails to match legacy non-segwit confidential liquid addresses such as  `VJL85kr4chhQBjKTzf8TE3nWnR1QaU93MzyjgzYkxAJiYrvajR5mDrJ9gUHvrd9DUozQzs88WWMpMdMp`
2) When using `esplora` backend, requesting `/api/v1/validate-address/VJL85kr4chhQBjKTzf8TE3nWnR1QaU93MzyjgzYkxAJiYrvajR5mDrJ9gUHvrd9DUozQzs88WWMpMdMp` returns 404

2021-09-06 21:41 UTC, wiz commented on backend/src/index.ts
> +        .get(config.MEMPOOL.API_URL_PREFIX + 'validate-address/:address', routes.validateAddress)
Shouldn't this be wrapped in a "if liquid enabled" statement?

2021-09-07 09:12 UTC, softsimon commented
>     1. Regex fails to match legacy non-segwit confidential liquid addresses such as  `VJL85kr4chhQBjKTzf8TE3nWnR1QaU93MzyjgzYkxAJiYrvajR5mDrJ9gUHvrd9DUozQzs88WWMpMdMp`
> 
Which regex? How do I reproduce the problem?

2021-09-07 15:38 UTC, wiz commented
Just search for the address I gave, the regex doesn't match so it doesn't try to lookup the unconfidential address for it.

2021-09-07 21:37 UTC, wiz approved these changes

2021-09-07 21:37 UTC, merged