Handle changes to address RPC api in bitcoin core 22
mempool/mempool pull request #779
Opened 2021-09-14 15:32 UTC by softsimon

fixes #778

This fix handles both the new core 22.0 and older version style of bitcoin addresses in the RPC API. 

This only happens when running with bitcoind as main backend.

2021-09-17 11:48 UTC, MiguelMedeiros requested changes

2021-09-17 11:48 UTC, MiguelMedeiros commented on backend/src/api/bitcoin/bitcoin-api.interface.ts
> +      address?: string              //  (string) bitcoin address
You forgot the semicolons.
```suggestion
      addresses?: string[];           //  (string) bitcoin addresses
      address?: string;              //  (string) bitcoin address
```

2021-09-17 11:59 UTC, MiguelMedeiros approved these changes

2021-09-17 12:04 UTC, MiguelMedeiros approved these changes

2021-09-17 12:20 UTC, wiz commented
@MiguelMedeiros How exactly did you go about testing this and which backend did you use? I am still waiting for my test environment to finish syncing

2021-09-17 12:59 UTC, MiguelMedeiros commented
> @MiguelMedeiros How exactly did you go about testing this and which backend did you use? I am still waiting for my test environment to finish syncing

Sorry for this approve!
I'm testing Github CLI and I made a wrong command twice!.  :(

I've just reviewed the code and concept ACK.

2021-09-17 14:52 UTC, MiguelMedeiros commented
@wiz @softsimon Tested ACK.

### Step-by-step:
1 - run bitcoin-core 0.21.1
2 - npm run build (backend)
3 - I've tested the same tx address from the issue to be sure that we solved the issue. http://localhost:4200/tx/3b8cf3202b2a5e35d0bec44d1bee8991e3cbebe3640b8f2d3115127d1522161a
4 - stopped the core and ran bitcoin-core 22.0.0
5 - npm run build (backend)
6 - I've tested the same tx address again.

### Preview images
#### Running Bitcoin-Core 22.0.0
![image](https://user-images.githubusercontent.com/5798170/133802955-2a31bc56-0902-4336-bee2-93882567c1d7.png)

#### Running Bitcoin-Core 0.21.1
![image](https://user-images.githubusercontent.com/5798170/133803256-ae8ef2b2-ee57-4b75-a82a-00aa8e6999f8.png)

2021-09-17 21:59 UTC, MiguelMedeiros approved these changes

2021-09-17 22:02 UTC, MiguelMedeiros approved these changes

2021-09-17 22:02 UTC, MiguelMedeiros approved these changes

2021-09-18 08:51 UTC, wiz approved these changes

2021-09-18 08:51 UTC, wiz approved these changes
utACK

2021-09-18 08:51 UTC, merged